version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: content-hub-db
    environment:
      POSTGRES_USER: contentuser
      POSTGRES_PASSWORD: localpassword
      POSTGRES_DB: content_hub_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U contentuser -d content_hub_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
